### ISSUE TITLE
Accessibility testing - Sim Daltonism

### ISSUE THREAD

**Issue by karenhodgkinson** [Sebby-T/ecommerce-pattern-library#8]
Your website makes me so happy. And also a little jealous. The only accessibility issues I found were with your nav link text... header nav doesn't indicate which page you are on (See screenshot #1), footer nav is too low-contrast for certain forms of colour blindness (See screenshot #2, 3), and your breadcrumb nav can be hard to see as well ((See screenshot #4, 5). Otherwise, great work!!

<img width="286" alt="screenshot-1" src="https://user-images.githubusercontent.com/31959335/56229284-93324300-6047-11e9-93b8-13e614a1ab9a.png">
<img width="664" alt="screenshot-2" src="https://user-images.githubusercontent.com/31959335/56229286-93324300-6047-11e9-83a3-41af50fa7a37.png">
<img width="661" alt="screenshot-3" src="https://user-images.githubusercontent.com/31959335/56229287-93324300-6047-11e9-91fe-799f4bd27c99.png">
<img width="587" alt="screenshot-4" src="https://user-images.githubusercontent.com/31959335/56229288-93324300-6047-11e9-8a50-46db843a5b8e.png">
<img width="496" alt="screenshot-5" src="https://user-images.githubusercontent.com/31959335/56229289-93324300-6047-11e9-8945-aee9112af87b.png">

**Comment by Sebby-T** [comment]
Thanks, Karen I appreciate that a lot! I've made the fixes
